---
- name: install and config dispatcher (apache based)
  hosts: all
  tasks:
    - name : Register with redhat
      redhat_subscription:
        state: present
        username: "{{ rhn user }}"
        password: "{{ rhn pass }}"
        pool_ids: 2c9280817af91203017b1d51f46307b5
